#!/usr/bin/env bash

set -eu

own_dir="$(readlink -f "$(dirname "$0")/..")"

effective_version="${EFFECTIVE_VERSION}"

echo "releasing ${effective_version}"

echo "releasing bindings-python to pypi"
"${own_dir}/release_to_pypi"
