#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -eu

own_dir="$(readlink -f "$(dirname "$0")")"

effective_version="${EFFECTIVE_VERSION}"

echo "releasing ${effective_version}"

echo "releasing bindings-python to pypi"
"${own_dir}/release_to_pypi"
