#!/usr/bin/env bash

set -ux

# assume this script resides one dir below repo-root
own_dir="$(readlink -f "$(dirname $0)")"
repo_root="$(readlink -f "${own_dir}/..")"

# set by pipeline to this dir, checked out for branch `github_pages`
out_dir="${GITHUB_PAGES_PATH}"


function sphinx_build {
  doc_dir="${repo_root}/doc"

  sphinx-build -E -a "${doc_dir}" "${out_dir}"
}

function schema_build {
  pip3 install json-schema-for-humans

  generate-schema-doc \
    "${repo_root}/component-descriptor-v2-schema.yaml" \
    "${out_dir}/component-descriptor-v2.html"
}

sphinx_build
schema_build

export GIT_DIR="${out_dir}/.git"
export GIT_WORK_TREE="${out_dir}"

if [ -z "$(git status --porcelain=v1)" ]; then
  echo "no changes - nothing to commit"
  exit 0
fi

git add .
git commit -m "update documentation"
