#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

own_dir="$(readlink -f "$(dirname "${0}")")"
repo_root="$(readlink -f "${own_dir}/..")"

cd ${repo_root}/bindings-go/

make install-requirements
go mod vendor

make check
make test

echo "All checks succeeded"
