#!/usr/bin/env sh
set -e

own_dir="$(readlink -f "$(dirname "${0}")")"
repo_root="$(readlink -f "${own_dir}/..")"

# XXX maybe we should pre-install this into the image?
apk add make

cd ${repo_root}/bindings-go/

make install-requirements
go mod vendor

make check
make test

echo "All checks succeeded"
